### ISSUE TITLE
Add CI workflow for testing on Windows runners

### ISSUE THREAD

**Issue by olaservo** [modelcontextprotocol/servers#1149]
### Is your feature request related to a problem? Please describe.

Many Windows-specific issues are hard to catch early since the current CI workflows only run on Ubuntu runners. This makes it difficult to verify Windows compatibility until issues are reported by users, leading to a slower feedback loop for Windows-related bugs.

### Describe the solution you'd like

Add Windows runners to the CI workflow by creating a new dedicated testing workflow that:
1. Runs tests on both Ubuntu and Windows using GitHub's hosted runners
2. Uses a matrix strategy to test both TypeScript and Python packages
3. Runs in parallel with existing build workflows
4. Provides early feedback on Windows compatibility for all PRs

Example workflow configuration:
```yaml
name: Cross-Platform Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-typescript:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm test
```

Disclaimer: This ^^ is a quickly edited Claude suggestion so it may contain syntax errors.

### Describe alternatives you've considered

1. **Modify existing workflows**: Add Windows runners to typescript.yml and python.yml
   - Pro: Keeps CI config in fewer files
   - Con: Makes existing workflows more complex

2. **Separate Windows-only workflows**
   - Pro: Simpler to maintain
   - Con: Duplicates config between OS-specific workflows

### Additional context

- Implementation can be done incrementally:
  1. Add Windows testing for TypeScript packages
  2. Extend to Python packages once TypeScript integration is verified
