### ISSUE TITLE
Postgres MCP server INVALID_URL error in Docker

### ISSUE THREAD

**Issue by fahadshery** [modelcontextprotocol/servers#1929]
Hi,

I am trying to setup the `src/postgres` MCP server using docker. 
Here is my `docker-compose.yml`:
```
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector
    hostname: postgres
    env_file:
      - .env
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
      - POSTGRES_DB=${POSTGRES_DB:-}
    volumes:
      - /home/user/ai-stack/postgresql/data:/var/lib/postgresql/data
      - /home/user/ai-stack/postgresql/init-scripts:/docker-entrypoint-initdb.d  # extensions setup
      - /home/user/ai-stack/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 1g
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-mcp-server:
    build:
      context: ./mcp_servers
      dockerfile: ./src/postgres/Dockerfile
    image: mcp/postgres
    container_name: postgres_mcp_server
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy
    command: ["node", "dist/index.js"]
```
I am getting `INVALID_URL` error. What am I doing wrong? My `postgres` container is accessible with no issues
