### ISSUE TITLE
Github MCP server session initialization

### ISSUE THREAD

**Issue by Kirankumar2609** [modelcontextprotocol/servers#1936]
I have setup github mcp server using docker along with other containers. Here is the docker file:
```
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cga_backend
    env_file:
      - .env.dev
    ports:
      - "8030:8030"
    volumes:
      - ./src:/app/
      - work_dir:/app/data
      # - shared-volume:/app/shared_volume
    restart: on-failure
    command: uvicorn main:app --host 0.0.0.0 --port 8030 --reload --log-level debug
    networks:
      - default
      
  postgres:
    image: pgvector/pgvector:0.7.0-pg16
    container_name: cga_postgres
    ports:
      - 6789:5432
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - default

  github-mcp:
    image: mcp/github-mcp-server
    container_name: mcp_server
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=****
      - GITHUB_TOOLSETS=repos
    stdin_open: true
    networks:
      - default
  
volumes:
  pgdata:
  work_dir:
  shared-volume:

networks:
  default:
```

I am trying to initialize a session using StdioServerParameters from mcp library. Here is the snippet:
```
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client        
async def connect_to_server(self):
       server_params = StdioServerParameters(
          command="docker",
          args=[
              "exec",
              "-it", # tried removing this
              "mcp_server",
              "./github-mcp-server", # tried giving the entire path - /server/github-mcp-server
              "stdio"
          ],
      )
      async with stdio_client(server_params) as (read, write):
          async with ClientSession(read, write) as session:
              self.session = session
              await session.initialize()
```

I am getting the error: 'FileNotFoundError: [Errno 2] No such file or directory' in the line: `async with stdio_client(server_params) as (read, write):`

In terminal, I am getting server running response:
```
$ docker exec -it mcp_server ./github-mcp-server stdio
GitHub MCP Server running on stdio
```

What am I doing wrong here?
