### ISSUE TITLE
MCP Implementation Issue: Multi-Client Docker Configuration

### ISSUE THREAD

**Issue by GratefulDave** [modelcontextprotocol/servers#446]
### Issue Description
Our implementation of MCP services in Docker is not properly handling shared connections between Claude and Cline clients. While the protocol implementation works with other MCP servers, our configuration is causing connection handling issues.

### Current Implementation
We're running three Docker containers:
```yaml
services:
  mcp-filesystem:          # Port 3004 (socket) / 3005 (http)
  mcp-sequentialthinking:  # Port 3002 (socket) / 3003 (http)
  mcp-shared-memory:       # Port 3000 (socket) / 3001 (http)
```

Client configs attempt to share these servers:
```json
{
  "mcpServers": {
    "filesystem": {
      "command": "socat",
      "args": ["STDIO", "TCP:localhost:3004"],
      "network": "host"
    },
    "sequentialthinking": {
      "command": "socat",
      "args": ["STDIO", "TCP:localhost:3002"],
      "network": "host"
    },
    "knowledgegraph": {
      "command": "socat",
      "args": ["STDIO", "TCP:localhost:3000"],
      "network": "host"
    }
  }
}
```

### Problem
1. Services accept initial connections but don't maintain them
2. Socket connections are being closed after initial handshake
3. Client requests receive no responses despite services logging receipt
4. Both Claude and Cline try to use same servers but can't maintain connections

### Investigation Findings
1. Connection sequence starts correctly:
```
mcp-filesystem | Socket connection established
mcp-filesystem | Received message: {
  method: 'initialize',
  params: {
    protocolVersion: '2024-11-05',
    capabilities: {},
    clientInfo: { name: 'claude-ai', version: '0.1.0' }
  },
  jsonrpc: '2.0',
  id: 0
}
```

2. However, subsequent requests fail despite being received:
```
mcp-filesystem | Received message: { method: 'tools/list', params: {}, jsonrpc: '2.0', id: 1 }
[no response sent]
```

### Key Differences from Working Implementations
1. Other implementations handle socket lifecycle differently
2. Working servers maintain persistent connections per client
3. Proper handling of shared memory state between clients

### Required Changes
1. Update Docker networking:
```yaml
services:
  mcp-filesystem:
    networks:
      - mcp-network
    ports:
      - "3004:3004"
      - "3005:3005"
    volumes:
      - type: bind
        source: ${PROJECT_ROOT:-${HOME}/projects}
        target: /projects
        read_only: false
```

2. Fix socket handling:
```typescript
export class SocketHandler {
    private clientId: string;
    private connections: Map<string, Socket> = new Map();

    constructor() {
        this.setupSocketServer();
    }

    private setupSocketServer(): void {
        const server = net.createServer((socket) => {
            socket.once('data', (data) => {
                const message = this.parseInitialMessage(data);
                if (message?.params?.clientInfo?.name) {
                    this.handleNewConnection(socket, message.params.clientInfo.name);
                }
            });
        });
    }
}
```

3. Update client configuration handling:
```typescript
private handleNewConnection(socket: Socket, clientId: string): void {
    if (this.connections.has(clientId)) {
        const existing = this.connections.get(clientId);
        existing?.end();
    }
    this.connections.set(clientId, socket);
    this.setupClientHandlers(socket, clientId);
}
```

### Action Items
1. Implement proper connection management per client
2. Update Docker networking configuration
3. Fix shared memory state handling
4. Add client identification handling
5. Implement proper socket lifecycle management

### Testing Plan
1. Run both Claude and Cline simultaneously
2. Verify shared memory persistence
3. Test concurrent access to filesystem
4. Verify sequential thinking requests work from both clients
5. Monitor connection stability over time

/label bug, implementation, high-priority
/assign @team-mcp-implementation

### References
- Working MCP server implementations
- MCP protocol specification
- Docker networking best practices
