### ISSUE TITLE
server-memory 0.6.3 is not available on npm

### ISSUE THREAD

**Issue by BRO3886** [modelcontextprotocol/servers#674]
**Describe the bug**
Unable to set the custom file path via npx since the npm registry does not have the latest version of server-memory

**To Reproduce**
- https://www.npmjs.com/package/@modelcontextprotocol/server-memory?activeTab=versions
- https://github.com/modelcontextprotocol/servers/commit/04209ec24813c063775bb4e0e9e51bc265d3bf1c

**Expected behavior**
0.6.3 should be available on NPM. Thanks a lot!

**Comment by edobez** [comment]
Related to #220

**Comment by IzumiSy** [comment]
Why isn't that published? I really need that.

**Comment by wcygan** [comment]
@ashwin-ant  @dsp-ant @jspahrsummers can this please have some attention? The fix is there, yet users are needlessly rolling-their-own because of the lack of support.

---

Context:

The commit https://github.com/modelcontextprotocol/servers/commit/04209ec24813c063775bb4e0e9e51bc265d3bf1c fixes the issue, but it has not yet been published to NPM. 

Package: https://www.npmjs.com/package/@modelcontextprotocol/server-memory
Collaborator 1: https://www.npmjs.com/~jspahrsummers
Collaborator 2: https://www.npmjs.com/~thedsp
Collaborator 3: https://www.npmjs.com/~ashwin-ant

**Comment by olaservo** [comment]
I opened a PR to trigger a publish to NPM here: https://github.com/modelcontextprotocol/servers/pull/1518

I believe there was some timing issue between when the auto-publish process was implemented and when the last code changes were made to the repo.  This should force a new version.

**Comment by wcygan** [comment]
Thank you @olaservo!

I notice that the GitHub Action for typescript publish is skipped, which seems like the culprit?

Ref: https://github.com/modelcontextprotocol/servers/actions/runs/14576064001/job/40882362621

<img width="1437" alt="Image" src="https://github.com/user-attachments/assets/fc0d3f1f-0abd-4275-a2c0-25b1441db451" />

Perhaps there is something wrong with the [typescript publish action](https://github.com/modelcontextprotocol/servers/blob/a95086b888e50e791063f04fb3e13f86acc6d479/.github/workflows/typescript.yml#L48)

Maybe it needs to have a release cut for it to trigger the publish?

```yaml
  publish:
    runs-on: ubuntu-latest
    needs: [build, detect-packages]
    if: github.event_name == 'release'
    environment: release

    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-packages.outputs.packages) }}
    name: Publish ${{ matrix.package }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        working-directory: src/${{ matrix.package }}
        run: npm ci

      - name: Publish package
        working-directory: src/${{ matrix.package }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
